import { createSlice } from "@reduxjs/toolkit";
import { useEffect } from "react";
import { Image } from "react-native";
const GaugeSlice = createSlice({
    name:'Gauge',
    
    initialState:{        
     Gauge_right:{
        0:require('../../assets/images/engine/gauge/right_0.png'),
        1:require('../../assets/images/engine/gauge/right_1.png'),
        2:require('../../assets/images/engine/gauge/right_2.png'),
        3:require('../../assets/images/engine/gauge/right_3.png'),
        4:require('../../assets/images/engine/gauge/right_4.png'),
        5:require('../../assets/images/engine/gauge/right_5.png'),
        6:require('../../assets/images/engine/gauge/right_6.png'),
        7:require('../../assets/images/engine/gauge/right_7.png'),
        8:require('../../assets/images/engine/gauge/right_8.png'),
        9:require('../../assets/images/engine/gauge/right_9.png'),
        10:require('../../assets/images/engine/gauge/right_10.png'),
        11:require('../../assets/images/engine/gauge/right_11.png'),      
        12:require('../../assets/images/engine/gauge/right_12.png'),  
        13:require('../../assets/images/engine/gauge/right_13.png'),  
        14:require('../../assets/images/engine/gauge/right_14.png'),  
        15:require('../../assets/images/engine/gauge/right_15.png'),  
        16:require('../../assets/images/engine/gauge/right_16.png'),  
        17:require('../../assets/images/engine/gauge/right_17.png'),  
        18:require('../../assets/images/engine/gauge/right_18.png'),  
        19:require('../../assets/images/engine/gauge/right_19.png'),  
        20:require('../../assets/images/engine/gauge/right_20.png'),  
        21:require('../../assets/images/engine/gauge/right_21.png'),  
        22:require('../../assets/images/engine/gauge/right_22.png'),  
        23:require('../../assets/images/engine/gauge/right_23.png'),  
        24:require('../../assets/images/engine/gauge/right_24.png'),  
        25:require('../../assets/images/engine/gauge/right_25.png'),  
        26:require('../../assets/images/engine/gauge/right_26.png'),  
        27:require('../../assets/images/engine/gauge/right_27.png'),  
        28:require('../../assets/images/engine/gauge/right_28.png'),  
        29:require('../../assets/images/engine/gauge/right_29.png'), 
        30:require('../../assets/images/engine/gauge/right_30.png'), 
        31:require('../../assets/images/engine/gauge/right_31.png'), 
        32:require('../../assets/images/engine/gauge/right_32.png'),
        33:require('../../assets/images/engine/gauge/right_33.png'),
        34:require('../../assets/images/engine/gauge/right_34.png'),
        35:require('../../assets/images/engine/gauge/right_35.png'),
        36:require('../../assets/images/engine/gauge/right_36.png'),
        37:require('../../assets/images/engine/gauge/right_37.png'),
        38:require('../../assets/images/engine/gauge/right_38.png'),
        39:require('../../assets/images/engine/gauge/right_39.png'),
        40:require('../../assets/images/engine/gauge/right_40.png'),
        41:require('../../assets/images/engine/gauge/right_41.png'),
        42:require('../../assets/images/engine/gauge/right_42.png'),
        43:require('../../assets/images/engine/gauge/right_43.png'),
        44:require('../../assets/images/engine/gauge/right_44.png'),
        45:require('../../assets/images/engine/gauge/right_45.png'),
        46:require('../../assets/images/engine/gauge/right_46.png'),
        47:require('../../assets/images/engine/gauge/right_47.png'),
        48:require('../../assets/images/engine/gauge/right_48.png'),
        49:require('../../assets/images/engine/gauge/right_49.png'),
        50:require('../../assets/images/engine/gauge/right_50.png'),
     },
     Gauge_left:{
        0:require('../../assets/images/engine/gauge/right_0.png'),
        1:require('../../assets/images/engine/gauge/right_1.png'),
        2:require('../../assets/images/engine/gauge/right_2.png'),
        3:require('../../assets/images/engine/gauge/right_3.png'),
        4:require('../../assets/images/engine/gauge/right_4.png'),
        5:require('../../assets/images/engine/gauge/right_5.png'),
        6:require('../../assets/images/engine/gauge/right_6.png'),
        7:require('../../assets/images/engine/gauge/right_7.png'),
        8:require('../../assets/images/engine/gauge/right_8.png'),
        9:require('../../assets/images/engine/gauge/right_9.png'),
        10:require('../../assets/images/engine/gauge/right_10.png'),
        11:require('../../assets/images/engine/gauge/right_11.png'),      
        12:require('../../assets/images/engine/gauge/right_12.png'),  
        13:require('../../assets/images/engine/gauge/right_13.png'),  
        14:require('../../assets/images/engine/gauge/right_14.png'),  
        15:require('../../assets/images/engine/gauge/right_15.png'),  
        16:require('../../assets/images/engine/gauge/right_16.png'),  
        17:require('../../assets/images/engine/gauge/right_17.png'),  
        18:require('../../assets/images/engine/gauge/right_18.png'),  
        19:require('../../assets/images/engine/gauge/right_19.png'),  
        20:require('../../assets/images/engine/gauge/right_20.png'),  
        21:require('../../assets/images/engine/gauge/right_21.png'),  
        22:require('../../assets/images/engine/gauge/right_22.png'),  
        23:require('../../assets/images/engine/gauge/right_23.png'),  
        24:require('../../assets/images/engine/gauge/right_24.png'),  
        25:require('../../assets/images/engine/gauge/right_25.png'),  
        26:require('../../assets/images/engine/gauge/right_26.png'),  
        27:require('../../assets/images/engine/gauge/right_27.png'),  
        28:require('../../assets/images/engine/gauge/right_28.png'),  
        29:require('../../assets/images/engine/gauge/right_29.png'), 
        30:require('../../assets/images/engine/gauge/right_30.png'), 
        31:require('../../assets/images/engine/gauge/right_31.png'), 
        32:require('../../assets/images/engine/gauge/right_32.png'),
        33:require('../../assets/images/engine/gauge/right_33.png'),
        34:require('../../assets/images/engine/gauge/right_34.png'),
        35:require('../../assets/images/engine/gauge/right_35.png'),
        36:require('../../assets/images/engine/gauge/right_36.png'),
        37:require('../../assets/images/engine/gauge/right_37.png'),
        38:require('../../assets/images/engine/gauge/right_38.png'),
        39:require('../../assets/images/engine/gauge/right_39.png'),
        40:require('../../assets/images/engine/gauge/right_40.png'),
        41:require('../../assets/images/engine/gauge/right_41.png'),
        42:require('../../assets/images/engine/gauge/right_42.png'),
        43:require('../../assets/images/engine/gauge/right_43.png'),
        44:require('../../assets/images/engine/gauge/right_44.png'),
        45:require('../../assets/images/engine/gauge/right_45.png'),
        46:require('../../assets/images/engine/gauge/right_46.png'),
        47:require('../../assets/images/engine/gauge/right_47.png'),
        48:require('../../assets/images/engine/gauge/right_48.png'),
        49:require('../../assets/images/engine/gauge/right_49.png'),
        50:require('../../assets/images/engine/gauge/right_50.png'),
     }
    },
    
    reducers:{        
        setGauge: (state, action) => {
         state.Gauge_right[action.payload.key] = action.payload.imagePath;
        },
        
    }
    
});

export const { setGauge } = GaugeSlice.actions;
export const selectGauge = (state) => state.Gauge.Gauge_right;
export default GaugeSlice.reducer;